<footer class="col-12" >
  <!-- Logos -->
  <div class="row text-center" id="sponsors">

    <div class="col-12">
      <div class="row align-items-center h-100">
          <div class="col-12 mx-auto">
              <img class="img-fluid sponsor-izq" src="images/branca.png" />
              <img class="img-fluid sponsor" src="images/johnnie.png" />
              <img class="img-fluid sponsor" src="images/smirnoff.png" />
              <img class="img-fluid sponsor" src="images/corona.png" />
              <img class="img-fluid sponsor-der" src="images/speed.png" />
          </div>
      </div>
    </div>

  </div>

  <!-- Texto -->
  <div class="row">

    <div class="col-12 text-center">

      <p>© 2018 Montevideo Music Box</p>

    </div>

  </div>
</footer>
